// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class NativeTemplateBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeTemplateBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeTemplateBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  int factorial(
    int n,
  ) {
    return _factorial(
      n,
    );
  }

  late final _factorialPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('factorial');
  late final _factorial = _factorialPtr.asFunction<int Function(int)>();

  int fibonacci(
    int n,
  ) {
    return _fibonacci(
      n,
    );
  }

  late final _fibonacciPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('fibonacci');
  late final _fibonacci = _fibonacciPtr.asFunction<int Function(int)>();
}
